# Generated by Django 6.0.4 on 2026-04-27 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledOrg',
            fields=[
                ('ein', models.TextField(primary_key=True, serialize=False)),
                ('first_crawled_at', models.TextField()),
                ('last_crawled_at', models.TextField()),
                ('candidate_count', models.IntegerField()),
                ('fetched_count', models.IntegerField()),
                ('confirmed_report_count', models.IntegerField()),
            ],
            options={
                'db_table': 'crawled_orgs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NonprofitSeed',
            fields=[
                ('ein', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('city', models.TextField(null=True)),
                ('state', models.TextField(null=True)),
                ('website_url', models.TextField(null=True)),
                ('website_candidates_json', models.TextField(null=True)),
                ('resolver_status', models.TextField(null=True)),
                ('resolver_confidence', models.FloatField(null=True)),
                ('resolver_method', models.TextField(null=True)),
                ('resolver_reason', models.TextField(null=True)),
                ('resolver_updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'nonprofits_seed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('content_sha256', models.TextField(primary_key=True, serialize=False)),
                ('source_org_ein', models.TextField()),
                ('source_url_redacted', models.TextField(null=True)),
                ('classification', models.TextField(null=True)),
                ('classification_confidence', models.FloatField(null=True)),
                ('archived_at', models.TextField()),
                ('file_size_bytes', models.BigIntegerField()),
                ('page_count', models.IntegerField(null=True)),
                ('report_year', models.IntegerField(null=True)),
                ('first_page_text', models.TextField(null=True)),
            ],
            options={
                'db_table': 'reports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PipelineAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('process_name', models.CharField(max_length=50)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('source_ip', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pipeline_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PipelineProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error')], default='stopped', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('log_file', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pipeline_processes',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(blank=True, max_length=2, null=True)),
                ('phase', models.CharField(choices=[('seed', 'Seed'), ('resolve', 'Resolve'), ('crawl', 'Crawl'), ('classify', 'Classify')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('host', models.CharField(default='localhost', max_length=100)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('log_file', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('progress_current', models.IntegerField(default=0)),
                ('progress_total', models.IntegerField(blank=True, null=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('depends_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='pipeline.job')),
            ],
            options={
                'db_table': 'jobs',
                'indexes': [models.Index(fields=['status', 'phase'], name='jobs_status_7d5000_idx'), models.Index(fields=['state_code', 'phase'], name='jobs_state_c_abbd3e_idx')],
            },
        ),
    ]
