# Generated by Django 6.0.4 on 2026-05-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_rename_reports_to_corpus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='phase',
            field=models.CharField(choices=[('seed', 'Seed'), ('resolve', 'Resolve'), ('crawl', 'Crawl'), ('classify', 'Classify'), ('990-enrich', '990 Enrich'), ('990-index', '990 Index'), ('990-parse', '990 Parse')], max_length=20),
        ),
    ]
